#!/bin/sh /etc/rc.common
# Copyright (C) 2019 OpenWrt.org

START=99
USE_PROCD=1

NAME=wrtbwmon
PID_FILE=/var/run/wrtbwmon.pid
args=/usr/sbin/wrtbwmon

_renamefile() {
	local base=$(basename -- "$1")
	local ext=$([ -z "${base/*.*/}"  ] && echo ".${base##*.}" || echo '')
	local base="${base%.*}"
	echo "$(dirname $1)/${base}$2$ext" && return
}

create_instance() {
	procd_open_instance
	procd_set_param command $args
	procd_set_param respawn
	procd_set_param user root
#	procd_set_param pidfile $PID_FILE
	procd_close_instance
}

service_triggers()
{
	procd_add_reload_trigger "$NAME"
}

start_service() {
	local db enabled
	config_load $NAME

	config_get db general path
	[ -z "$db" ] && db="/tmp/usage.db"
	append args " -46"
	append args "-f $db"
	append args "-p /tmp/usage.htm"
	append args "-u /etc/wrtbwmon.user"
	append args "-d"

	config_get enabled  general enabled
	[ "$enabled"0 -eq 0 ] || create_instance
}

stop_service() {
	procd_kill wrtbwmon
	kill -CONT $(cat $PID_FILE)
}

reload_service() {
	if running; then
		. /usr/share/libubox/jshn.sh
		json_init
		json_load "$(ubus call service list '{"name":"wrtbwmon"}' | jsonfilter -e @.*.*.*)"
		export -n command
		json_select command
		json_get_values command
		local oldPath="$(echo $command | sed -n 's/.*\-f \(\S\+\).*/\1/gp')"
		local newPath=$(uci -q get wrtbwmon.general.path)
		[ "$oldPath" = "${newPath:-/tmp/usage.db}" ] || {
			mv "$oldPath" "${newPath:-/tmp/usage.db}"
			mv "$(_renamefile $oldPath .6)" "$(_renamefile ${newPath:-/tmp/usage.db} .6)"
			mv "$(_renamefile $oldPath .46)" "$(_renamefile ${newPath:-/tmp/usage.db} .46)"
		}
		json_cleanup
	fi
	stop
	start
}
