#!/bin/sh /etc/rc.common
#
# start/stop wrtbwmon bandwidth monitor

### BEGIN INIT INFO
# Provides:           wrtbwmon
# Required-Start:     $network $local_fs $remote_fs
# Required-Stop:      $local_fs $remote_fs
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  iptables-based bandwidth monitor
### END INIT INFO

START=91

start(){
    if [ $( uci get wrtbwmon.general.persist ) == 1 ]
    then
        /usr/sbin/wrtbwmon setup /etc/config/usage.db /tmp/usage.htm /etc/wrtbwmon.user >> /dev/null 2>&1 &
    else
        /usr/sbin/wrtbwmon setup /tmp/usage.db /tmp/usage.htm /etc/wrtbwmon.user >> /dev/null 2>&1 &
    fi
}

stop(){
    /usr/sbin/wrtbwmon remove
}
