#!/bin/sh
#

case $1 in
    "setup" )
        if [ -e /var/run/wrtbwmon.pid ]
        then
            echo "Another wrtbwmon is on running!!!"
        else
	    echo $$ > /var/run/wrtbwmon.pid
            i=0
            while [ $i -le 1 ];do
                if [ -z "$(iptables-save | grep RRDIPT)" ]; then
                    wrtbwmon1 setup $2
                fi

                pidnum=$( ps | grep wrtbwmon | wc -l )
                if [ $pidnum -le 3 ];then
                    wrtbwmon1 update $2
                fi
                sleep 10
            done
        fi

	;;

    "publish" )
        if [ -z "$(iptables-save | grep RRDIPT)" ]; then
            wrtbwmon1 setup $2
        fi

        if [ $( ps | grep wrtbwmon | wc -l ) -le 7 ];then
            wrtbwmon1 update $2 $4
        fi


	;;


    "remove" )
        wrtbwmon1 remove
        if [ -e '/var/run/wrtbwmon.pid' ]; then
            kill -9 $( cat /var/run/wrtbwmon.pid ) >> /dev/null 2>&1
        fi


        rm -f /var/run/wrtbwmon.pid >> /dev/null 2>&1
	;;

    *)
	echo \
"Usage: $0 {setup|update|publish|remove} [options...]

Options:
   $0 setup publish database_file path_of_html_report [user_file]

Examples:
   $0 setup /tmp/usage.db /www/user/usage.htm /jffs/users.txt
   $0 remove

Note: [user_file] is an optional file to match users with MAC addresses.
       Its format is \"00:MA:CA:DD:RE:SS,username\", with one entry per line."
	;;
esac
